global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 15s
  query_log_file: /prometheus/query.log
scrape_configs:
  - job_name: axon-server
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - axon-server-1:8024
  - job_name: axon-app
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - service-participants:8080
          - service-auction-object-registry:8080
          - service-auction-query:8080
          - service-auctions:8080
          - service-auctions:8080
          - service-interfaces:8080
